### ISSUE TITLE
Total Licensing Count is Incorrect

### ISSUE THREAD

**Issue by gconsultingadmin** [KelvinTegelaar/CIPP#1817]
### Description

1. select All Tenants from dropdown menu
2. Go to Reports > Licence Report

The license total is incorrect for customer who have a combination of monthly and yearly licensing. 
![image](https://github.com/KelvinTegelaar/CIPP/assets/141377603/65424aca-9112-45b1-a7e7-b4b983364602)

### Environment data

```PowerShell
Non-sponsored instance
Front end version number: 4.4.0
Back end version number: 4.4.0
Tried Tenant Cache Clear: false
Tried Token Cache Clear: false
```

**Comment by gconsultingadmin** [comment]
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment]
Fixed in dev

**Comment by gconsultingadmin** [comment]
I'm still having this same issue, is there anything I should check?

**Comment by gconsultingadmin** [comment]
@KelvinTegelaar 

The issue is this line:
https://github.com/KelvinTegelaar/CIPP-API/blob/73e032d6f29e1777d21e0062765927b76a392bfe/Modules/CIPPCore/Public/Get-CIPPLicenseOverview.ps1#L58

I added " - $($Term)" to the naming of the rowkey, so that monthly/yearly rows do not overwrite each other.
