### ISSUE TITLE
[Bug]: Can't deploy CA policies with group exclusion

### ISSUE THREAD

**Issue by TargetCrafter** [KelvinTegelaar/CIPP#3614]
### Required confirmations before submitting

- [x] **I can reproduce this issue on the latest released versions** of both CIPP and CIPP-API.
- [x] **I have searched existing issues** (both open and closed) to avoid duplicates.
- [x] I am **not** requesting general support; this is an actual bug report.

### Issue Description

I can't deploy CA policies via the deployment tool when the CA policy has a group. It looks like the quotes are not correctly escaped when doing this.
Note that this word without a problem via te standards.

![Image](https://github.com/user-attachments/assets/6670b5cf-9cea-4d8c-b4ab-14ae87089c3d)

1. Setup a Template Library
2. Create a CA policy with a group exclusion in the Library tenant
3. Deploy the CA policy using either via the CA deployment tool
4. Error

### Environment Type

Sponsored (paying) user

### Front End Version

7.1.3

### Back End Version

7.1.3

### Relevant Logs / Stack Trace

```plaintext

```

**Comment by KelvinTegelaar** [comment]
Cant seem to replicate this - Are you using \'s in group names?

**Comment by KelvinTegelaar** [comment]
I was looking at ca templates because of your description, but its groups. Checking this out :)

**Comment by TargetCrafter** [comment]
My bad. We ran into the issue because we had to deploy the groups to be able to deploy CA policies that contain the group.

**Comment by JohnDuprey** [comment]
@TargetCrafter can you try to delete the group template and re-create it? We were unable to reproduce this.

**Comment by TargetCrafter** [comment]
I setup the template library, and here i saw that the group name was surrounded by 6 slashes to escape the quote characters:
```json
(user.userPrincipalName -contains \\\\\\\"awesomeuser\\\\\\\")
```

Then i deleted the group, and recreated it via the interface before exporting it again, and there i saw that only 3 slashes were added:
```json
(user.userPrincipalName -contains \\\"awesomeuser\\\")
```

So somewhere in CIPP these slashes were added, but recreating the group solved the issue. So the problem is solved, and the cause is clear, but i don't know where or when this happened, as it worked before.

**Comment by TargetCrafter** [comment]
Running into the issue again now, but for a different tenant.

The error CIPP shows in the logbook is now as follows:
```
Failed to create or update conditional access rule 🟢Require MFA for all users: 1054: Invalid group value: . 
```

The groups have been deployed to the tenant, and CIPP should match those by display name as far as i know, so i don't get why it tries to find a group called "." when there is no such group in the CA template:

```json
{
    "id": "*****",
    "displayName": "🟢Require MFA for all users",
    "createdDateTime": "2024-10-01T16:01:56.90419Z",
    "modifiedDateTime": "2024-11-13T08:37:38.5835892Z",
    "state": "enabled",
    "conditions": {
        "userRiskLevels": [],
        "signInRiskLevels": [],
        "clientAppTypes": [
            "all"
        ],
        "platforms": null,
        "locations": null,
        "times": null,
        "deviceStates": null,
        "devices": null,
        "clientApplications": null,
        "applications": {
            "includeApplications": [
                "All"
            ],
            "excludeApplications": [],
            "includeUserActions": [],
            "includeAuthenticationContextClassReferences": [],
            "applicationFilter": null
        },
        "users": {
            "includeUsers": [
                "All"
            ],
            "excludeUsers": [],
            "includeGroups": [],
            "excludeGroups": [
                "📷Teams Meeting rooms",
                "🔗On-Prem Sync users"
            ],
            "includeRoles": [],
            "excludeRoles": [],
            "includeGuestsOrExternalUsers": null,
            "excludeGuestsOrExternalUsers": null
        }
    },
    "grantControls": {
        "operator": "OR",
        "builtInControls": [
            "mfa"
        ],
        "customAuthenticationFactors": [],
        "termsOfUse": [],
        "authenticationStrength@odata.context": "https://graph.microsoft.com/beta/$metadata#conditionalAccess/policies('cfa74063-2e56-4ac9-b1b5-f0cc976110f5')/grantControls/authenticationStrength/$entity",
        "authenticationStrength": null
    },
    "LocationInfo": [
        null,
        null
    ]
}
```

So perhaps something's wrong with the group matching?

**Comment by JohnDuprey** [comment]
this should be fixed in dev, it's possible the groups were not matching and causing a null value to be sent in the payload

**Comment by cdp86EC** [comment]
Hello,

I've just got the same problem and confirm it is still present. Pushed the groups via CIPP and while deploying CAPs, receiving the 1054: Invalid group value" error. Is there any work ongoing to fix the problem?

> Failed to add Conditional Access Policy . Error: Failed to create or update conditional access rule CA001: Requires MFA for Admins: 1054: Invalid group value: sg_MFA_exclusion.

> {
>   "id": "x",
>   "templateId": "x",
>   "displayName": "CA001: Requires MFA for Admins",
>   "createdDateTime": "2024-10-21T10:17:20.3438418Z",
>   "modifiedDateTime": "2024-11-08T15:23:43.5978549Z",
>   "state": "enabled",
>   "conditions": {
>     "userRiskLevels": [],
>     "signInRiskLevels": [],
>     "clientAppTypes": [
>       "all"
>     ],
>     "applications": {
>       "includeApplications": [
>         "All"
>       ],
>       "excludeApplications": [],
>       "includeUserActions": [],
>       "includeAuthenticationContextClassReferences": []
>     },
>     "users": {
>       "includeUsers": [],
>       "excludeUsers": [],
>       "includeGroups": [],
>       **"excludeGroups": [
>         "sg_MFA_exclusion"
>       ],**
>       "includeRoles": [
>         "62e90394-69f5-4237-9190-012177145e10",
>       ],
>       "excludeRoles": []
>     }
>   },
>   "grantControls": {
>     "operator": "OR",
>     "builtInControls": [
>       "mfa"
>     ],
>     "customAuthenticationFactors": [],
>     "termsOfUse": [],
>     "authenticationStrength@odata.context": "https://graph.microsoft.com/beta/$metadata#conditionalAccess/policies('x')/grantControls/authenticationStrength/$entity"
>   },
>   "sessionControls": {
>     "signInFrequency": {
>       "value": 8,
>       "type": "hours",
>       "authenticationType": "primaryAndSecondaryAuthentication",
>       "frequencyInterval": "timeBased",
>       "isEnabled": true
>     }
>   },
>   "LocationInfo": [],
>   "GUID": "x"
> }

**Comment by TargetCrafter** [comment]
@cdp86EC
This issue has been fixed in te latest release 7.4.1, I just tested it.

**Comment by rhinodp** [comment]
I am having this issue - Failed to create or update conditional access rule Block Non-US Sign-ins and Require MFA: 1054: Invalid user value: cipp_service_account. If I exclude the user value it will work. However, I cannot edit a deployed CA from CIPP.
