### ISSUE TITLE
[Bug]: Add ShortCut to Onedrive naming error (doesnt name it Library - Site, instead repeats Site - Site)

### ISSUE THREAD

**Issue by DavidHGAK** [KelvinTegelaar/CIPP#3845]
### Required confirmations before submitting

- [x] **I can reproduce this issue on the latest released versions** of both CIPP and CIPP-API.
- [x] **I have searched existing issues** (both open and closed) to avoid duplicates.
- [x] I am **not** requesting general support; this is an actual bug report.

### Issue Description

We love "Add shortcut to Onedrive" from the CIPP user management options however unlike when adding this from the web portal from within the users account, when taking this action from within CIPP it names the shortcut incorrectly. 

Should be: 
**"Documents - Site"**
Instead its naming them: 
**"Site - Site"** 
just repeating the Site name. This leads to a few problems like for example if there are more than one document libraries within a site there will be no way to distinguish. Also we have some users who still rely on copying paths and save Onedrive to a custom location on the C: drive and this is breaking that method. 

### Environment Type

Sponsored (paying) user

### Front End Version

7.3.2

### Back End Version

7.3.2

### Relevant Logs / Stack Trace

```plaintext

```

**Comment by JohnDuprey** [comment]
This is fixed in dev

**Comment by DavidHGAK** [comment]
Close but not working all the way just yet. 

Now its adding it with:
**Documents - Shared** 
However this document library was renamed to "Docs" rather than the default "Documents" so it should be:
**Docs - Shared**

So it looks like its not retrieving the name of the document library possibly just entering in the default of "Documents"? I am looking for a way to view the graph command to see.

**Comment by DavidHGAK** [comment]
Looks like this is still an issue. It adds the document library as "Documents" regardless of the name of that library. The site name is correct but the same example from above applies. They renamed the doc library "Docs" but its getting added as "Documents".
