### ISSUE TITLE
[Feature Request]: tables not working in HaloPSA tickets

### ISSUE THREAD

**Issue by isgq-github01** [KelvinTegelaar/CIPP#4243]
### Please confirm:

- [x] **I have searched existing feature requests** (open and closed) and found no duplicates.
- [x] **me or my organization is currently an active sponsor of the product at the $99,- level.

### Problem Statement

We raised this with the helpdesk but they advised it was more of a feature request. Alerts that contain tables are not parsed in HaloPSA correctly, so you end up with alert text that looks like this:

![Image](https://github.com/user-attachments/assets/4f097987-7839-478b-a296-6147ce6e96b2)

### Benefits for MSPs

Benefits MSPs in simpler legibility of alerts and easier to understand the information that is presented.

### Value or Importance

I believe this is critical as it's making the alert rather unusable, unfortunately.

**Comment by KelvinTegelaar** [comment]
Are you using email to your PSA instead of the PSA option, this is how it looks in Halo when you use the PSA option:

![Image](https://github.com/user-attachments/assets/abba207a-dbf6-4ccc-9fc1-e4b3398faa8c)

This looks more to be a configuration issue in HaloPSA.

**Comment by isgq-github01** [comment]
@KelvinTegelaar I believe it might just be the app approval alerts, at least? This alert looks fine for instance.

![Image](https://github.com/user-attachments/assets/48462c4d-e3e4-447c-a537-b8666a037c51)

**Comment by isgq-github01** [comment]
Also forgot to answer the question that yes we are using the direct to PSA option - not email to PSA

**Comment by KelvinTegelaar** [comment]
fixed in dev

**Comment by isgq-github01** [comment]
@KelvinTegelaar have found the "expiring app secrets" alert has the same problem, just in case your fix was only applied to the app consent request alerts. Tried searching the dev branch but couldn't find where your changes were :)

**Comment by isgq-github01** [comment]
Unfortunately this issue still seems to be present for both app consent requests and expiring app secrets. Tried a fresh app consent request and it's coming through to Halo as plain text. Definitely on 8.1.0. Let me know if you need any more info? @KelvinTegelaar @Zacgoose
