### ISSUE TITLE
[Bug]: Deny Deviation standard from drift on Tenant dont "run" and set the Drift standard = Non-compliances status

### ISSUE THREAD

**Issue by jhravnit** [KelvinTegelaar/CIPP#4866]
### Required confirmations before submitting

- [x] **I can reproduce this issue on the latest released versions** of both CIPP and CIPP-API.
- [x] **I have searched existing issues** (both open and closed) to avoid duplicates.
- [x] I am **not** requesting general support; this is an actual bug report.

### Issue Description

<p data-start="218" data-end="343">We are experiencing issues with the <strong data-start="273" data-end="291">Drift Template</strong> feature in CIPP when applied to multiple tenants.</p>
<p data-start="345" data-end="448">A Drift Template was created containing <strong data-start="385" data-end="401">54 standards</strong>, which was then assigned to several tenants:</p>
<ul data-start="449" data-end="646">
<li data-start="449" data-end="553">
<p data-start="451" data-end="553"><strong data-start="451" data-end="467">51 standards</strong> are configured with <strong data-start="488" data-end="551">&ldquo;Automatically remediate or deploy when drift is detected.&rdquo;</strong></p>
</li>
<li data-start="554" data-end="646">
<p data-start="556" data-end="646"><strong data-start="556" data-end="571">3 standards</strong> are configured with <strong data-start="592" data-end="614">&ldquo;Deny Remediation&rdquo;</strong> in the Tenant Drift Template.</p>
</li>
</ul>
<p data-start="648" data-end="870">The problem occurs with the 3 standards where <strong data-start="694" data-end="725">&ldquo;Deny Deviation from Drift&rdquo;</strong> is selected in at Tenanats Drift template. These standards remain <strong data-start="761" data-end="778">non-compliant</strong>, even though they should be marked as compliant according to the &ldquo;Golden&rdquo; drift template.</p>
<p data-start="872" data-end="963">In the <strong data-start="879" data-end="915">&ldquo;Policies and Settings Deployed&rdquo;</strong> section, the affected standards only show as:</p>
<blockquote data-start="964" data-end="1072">
<p data-start="966" data-end="1072"><em data-start="966" data-end="983">Deviation - New</em><br data-start="983" data-end="986" /> and they are <strong data-start="999" data-end="1016">never updated</strong> to match the compliance state of the Golden template.</p>
</blockquote>
<p data-start="1074" data-end="1361">When we modify one of these non-compliant standards and instead enable <strong data-start="1145" data-end="1207">&ldquo;Automatically remediate or deploy when drift is detected&rdquo;</strong>, it is immediately applied and becomes compliant &mdash; confirming the issue is related to the <strong data-start="1298" data-end="1318">&ldquo;Deny Deviation&rdquo;</strong> functionality not being enforced properly.</p>
<p data-start="1363" data-end="1396"><strong data-start="1363" data-end="1394">Example Standards Affected:</strong></p>
<div class="_tableContainer_1rjym_1">
<div class="group _tableWrapper_1rjym_13 flex w-fit flex-col-reverse" tabindex="-1">Disable SMTP Basic Authentication | "Message": "SMTP Basic Authentication for tenant is not disabled" + "Message": "SMTP Basic Authentication for all users is disabled"</div>
<div class="group _tableWrapper_1rjym_13 flex w-fit flex-col-reverse" tabindex="-1">Yes Enable or disable 'external' warning in Outlook | "Enabled": true, "AllowList": []</div>
<div class="group _tableWrapper_1rjym_13 flex w-fit flex-col-reverse" tabindex="-1">Yes Disables SMS as an MFA method | This setting is not configured correctly | Yes</div>
</div>
<p data-start="1892" data-end="2090"><strong data-start="1892" data-end="1914">Expected Behavior:</strong><br data-start="1914" data-end="1917" /> When &ldquo;Deny Deviation from Drift&rdquo; is set to <strong data-start="1960" data-end="1967">Yes</strong> in a Tenant Drift Template, the affected standards should be aligned and marked as <strong data-start="2051" data-end="2064">compliant</strong> with the Golden template.</p>
<p data-start="2092" data-end="2273"><strong data-start="2092" data-end="2112">Actual Behavior:</strong><br data-start="2112" data-end="2115" /> Standards with &ldquo;Deny Deviation from Drift&rdquo; remain <strong data-start="2165" data-end="2182">non-compliant</strong>, never applying the expected configuration, and stay stuck in the &ldquo;Deviation - New&rdquo; state.</p>
<p data-start="2275" data-end="2416"><strong data-start="2275" data-end="2286">Impact:</strong><br data-start="2286" data-end="2289" /> This prevents consistent configuration enforcement across tenants and undermines compliance alignment with the Golden template.</p>

### Environment Type

Sponsored (paying) user

### Front End Version

v8.6.1

### Back End Version

v8.6.1

### Relevant Logs / Stack Trace

```plaintext

```

**Comment by KelvinTegelaar** [comment]
Resolved in dev

**Comment by jhravnit** [comment]
> Resolved in dev

I still don’t see these standards working when we try to create a deviation using a Drift template. You’ve marked the issue as “Resolved in dev” — what does that mean? Is there anything we can do differently, or can we expect this to be included in a release, and if so, when?
