### ISSUE TITLE
[Bug]: Cloned Templates cannot be edited, as the Editor is missing. 

### ISSUE THREAD

**Issue by xenadmin** [KelvinTegelaar/CIPP#5017]
### Required confirmations before submitting

- [x] **I can reproduce this issue on the latest released versions** of both CIPP and CIPP-API.
- [x] **I have searched existing issues** (both open and closed) to avoid duplicates.
- [x] I am **not** requesting general support; this is an actual bug report.

### Issue Description

Since the button to clone templates appeared on our CIPP instance, the button to Edit Templates doesn't work anymore. 

<img width="309" height="308" alt="Image" src="https://github.com/user-attachments/assets/b173e78d-5f47-4498-9be3-36fb92416081" />

<img width="1754" height="453" alt="Image" src="https://github.com/user-attachments/assets/5e5ce549-5a60-41a2-a1bb-fe61214bcac6" />

Before the clone button was introduced, there was a simple GUI in CIPP frontend, to Edit templates. Since this button appeared in our frontend, any way to edit templates in CIPP is gone. Is this a bug or a feature?
I would need an answer here, because I need to know if I know need some form of golden/management tenant, to edit the polices I cloned. Without an editor, the clone is useless to us. They are just an identical copy with way to alter anything, now
I also double-checked the docs, and they don’t mention the clone template feature at all. 
So I’m helpless here. 

### Environment Type

Sponsored (paying) user

### Front End Version

v8.7.2

### Back End Version

v8.7.2

### Relevant Logs / Stack Trace

```plaintext

```

**Comment by KelvinTegelaar** [comment]
Fixed in dev.

**Comment by xenadmin** [comment]
Hi @KelvinTegelaar and Happy new Year! I'm back from vacation and verified this in our Tenant. 
We are on version v8.8.2 and the issue persists. 

<img width="755" height="468" alt="Image" src="https://github.com/user-attachments/assets/e614d7b9-01e1-47fa-9e54-94fedbf3a474" />

See here:

<img width="2025" height="521" alt="Image" src="https://github.com/user-attachments/assets/6a2598a6-1c6c-4876-9df6-e4d7f20a945b" />

In which version is this fix going to be shipped? Thank you for looking into this!
